# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  password:

development:
  <<: *default
  database: wright_development

test:
  <<: *default
  database: wright_test

production:
  <<: *default
  database: wright_production
