# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd5ff774c7d943aa08e412308aef58f98cb599af8e6f43f464e2cbfd8550f443d32c9a9391db40170f9372c72ff23a2656dd2128be5429ad0b3fb2927507966b

test:
  secret_key_base: 78d9139921f0955e441dbd675f7ce20d0566303743c9d2b5bff13449511a231de9931cc11876c840f873fe11db4b72d8c50b8c2c829332986c846e39bfa95a87

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
